### ISSUE TITLE
502 EOF error for websocket connection

### ISSUE THREAD

**Issue by princemaple** [mholt/caddy#1150]
### 1. What version of Caddy are you running (`caddy -version`)?
0.9.3

### 2. What are you trying to do?
using caddy as a reverse proxy

### 3. What is your entire Caddyfile?
```text
http://docker.dev {
  redir https://docker.dev
}

https://docker.dev {
  log stdout

  rewrite {
    ext .js .css .ico .jpg .png .txt
    to  /static/{path} {uri}
  }

  proxy /phoenix/live_reload/socket web:4000 {
    transparent
    websocket
  }

  proxy /socket/websocket web:4000 {
    transparent
    websocket
  }

  proxy / web:4000 {
    except /static
    transparent
  }

  root /var/www/html

  gzip

  tls /var/dev/cert.crt /var/dev/cert.key
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
`docker-compose up` (the docker-compose file is not important in this case, you can probably ignore it.)
```yml
version: '2'
services:
  caddy:
    image: abiosoft/caddy:0.9.3
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./priv/static:/var/www/html/static
      - ./dev:/var/dev
      - ./dev/Caddyfile.dev:/etc/Caddyfile
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
      args:
        - MIX_ENV=dev
    image: refbook
    ports:
      - 4000
    volumes:
      - ./web:/var/app/web
      - ./config:/var/app/config
      - ./priv:/var/app/priv
      - ./lib:/var/app/lib
      - ./test:/var/app/test
      - ./mix.exs:/var/app/mix.exs
      - ./mix.lock:/var/app/mix.lock
    depends_on:
      - db
  db:
    image: postgres:9.5.3
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - pg_data:/var/lib/postgresql/data:rw
  assets:
    build:
      context: .
      dockerfile: Dockerfile.assets
    image: refbook_assets
    volumes:
      - ./web/static:/var/build/src
      - ./priv/static/dist:/var/build/dist
      - ./package.json:/var/build/package.json
      - ./webpack.config.js:/var/build/webpack.config.js
      - ./tsconfig.json:/var/build/tsconfig.json
    command: npm run build:dev
volumes:
  pg_data:
    driver: local
```

**note: both code blocks in question 5 and question 6 are from the same running app, it's weird that the live_reload connection works, but my app connection doesnt... both of them connect to the same app server.**
**And, before 0.9.3 it also had this 502 problem but was reporting unreachable backend instead of EOF. In both cases, the request never made it to the app server (upstream)**

### 5. What did you expect to see?
something like this
```
caddy_1   | 172.18.0.1 - [28/Sep/2016:03:15:28 +0000] "GET /phoenix/live_reload/socket/websocket?vsn=1.0.0 HTTP/1.1" 200 0
```

### 6. What did you see instead (give full error messages and/or log)?
```
caddy_1   | 28/Sep/2016:03:17:32 +0000 [ERROR 502 /socket/websocket] EOF
caddy_1   | 172.18.0.1 - [28/Sep/2016:03:17:32 +0000] "GET /socket/websocket?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ2ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJhYmMiLCJpZCI6IjU2NTgxNDg1LTA4YjktNGM0Yi1hNGI5LTgzOTJmMTBmOTk3MSIsImV4cCI6MTQ3NzYyNDUxOCwiZW1haWwiOiJhYmNAZGVmLmNvbSIsImJ1c2luZXNzX2lkIjoiNjc1MTQzY2QtOTJmMC00NDBlLWJlNGYtOTJmMjg1ODQ2OWM3In0.aBmi3OC_lzdAUThcXcNDBnHf4nDo1JfCRxKna5hfSUA&vsn=1.0.0 HTTP/1.1" 502 40
````

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
I'm not sure.
