### ISSUE TITLE
Caddy has problems with ws: proxy urls

### ISSUE THREAD

**Issue by InAnimaTe** [mholt/caddy#1181]
### 1. What version of Caddy are you running (`caddy -version`)?

0.9.3
### 2. What are you trying to do?

I linked a container, making the name `ws` which is linked properly, contactable, and curl's to my websocket container perfectly (from inside the caddy container).

However, with this caddy config, **caddy seems to timeout, eventually returning a 502** ;(

```
cooldomain.net {                                                   
    proxy / ws:9999 {                                             
        transparent                                                         
        websocket                                                           
        header_upstream Sec-WebSocket-Protocol {>Sec-WebSocket-Protocol}    
        header_upstream Sec-WebSocket-Extensions {>Sec-WebSocket-Extensions}
    }                                                                       
    tls {                                                                   
        max_certs 1                                                         
    }                                                                       
}                                                                           
```
### 4. How did you run Caddy (give the full command and describe the execution environment)?

Inside a container, abiosoft's to be exact (how I usually run it)

```
-conf="/etc/Caddyfile" -http2=false -log=stdout
```
### 5. What did you expect to see?

This should just plain work. The websocket server container was merely a simple wscat container I linked with my caddy container. I entered the caddy container and it was perfectly contactable...curl even returned the upgrade required header etc..

So, after trying to get it to work for a while. I said to myself: "hmm, I really hope this _isn't_ the problem but what if caddy is having a problem with just a two character hostname to proxy to....". You can figure out what happened after that (I called the link `websocketftw` instead of `ws`, which worked perfectly :| )

To be clear, **this works perfectly**:

```
cooldomain.net {                                                   
    proxy / websocketftw:9999 {                                             
        transparent                                                         
        websocket                                                           
        header_upstream Sec-WebSocket-Protocol {>Sec-WebSocket-Protocol}    
        header_upstream Sec-WebSocket-Extensions {>Sec-WebSocket-Extensions}
    }                                                                       
    tls {                                                                   
        max_certs 1                                                         
    }                                                                       
}                                                                           

```
### 6. What did you see instead (give full error messages and/or log)?

Hanging when trying to connect (not sure how long; maybe 15-30 seconds) then a 502. I tried `wscat -c` as well as my browser extension.
### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

Here is pretty much the just of my `docker-compose.yml`

```
caddy:
    image: abiosoft/caddy:0.9.3
    restart: always
    volumes:
        - ./Caddyfile:/etc/Caddyfile
        - ./caddydata:/root/.caddy
    container_name: caddyproxy
    command: -conf="/etc/Caddyfile" -http2=false -log=stdout
    ports:
        - "44443:443"
    links:
        - ws
ws:
    image: joshgubler/wscat
    command: -l 9999
    tty: true
    expose:
        - "9999"
    ports:
        - "9999:9999"

```

You can then jump in your caddy container, `caddyproxy` via `docker exec -it caddyproxy /bin/ash` and view your hosts file, ping, or curl the `ws` domain.
