### ISSUE TITLE
Caddy not responding

### ISSUE THREAD

**Issue by HazCod** [mholt/caddy#1397]
### 1. What version of Caddy are you running (`caddy -version`)?
0.9.5

### 2. What are you trying to do?
run caddy in front of php-fpm and serve assets.

### 3. What is your entire Caddyfile?
```text
https://localhost/ {
    tls self-signed
    log stdout
    errors stderr

    header / {
        "Strict-Transport-Security" "max-age=63072000; includeSubdomains; preload"
        "X-Frame-Options" "DENY"
        "X-Content-Type-Options" "nosniff"
        "X-XSS-Protection" "1; mode=block"
        "Access-Control-Allow-Origin" "{host}"
        "Access-Control-Allow-Methods" "GET, POST, OPTIONS"
        -Server
    }

    gzip
    minify

    rewrite / {
        regexp .*
        to /index.php{uri}
    }

    fastcgi / php:8080 php {
        env HTTP_PROXY ""
        env SCRIPT_FILENAME /source/index.php
    }
}

https://localhost/asset/ {
    tls self-signed
    header / -Server
    errors stderr

    gzip
    minify

    root /asset/
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
```
HOME=/etc/caddy/ cap_net_bind_service=+ep \
    /etc/caddy/caddy \
    -conf /etc/caddy/caddyfile \
    -email "${EMAIL}" \
    -agree
```

### 5. What did you expect to see?
Request on 80 returns redirect to 443, request on 443 returns content.

### 6. What did you see instead (give full error messages and/or log)?
```
web_1  | Running Caddy 0.9.5
web_1  | Activating privacy features... done.
web_1  | https://localhost/
web_1  | https://localhost/asset/
```

and test:
```
~$ curl -v http://localhost/
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 80 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 80 (#0)
> GET / HTTP/1.1
> Host: localhost
> User-Agent: curl/7.51.0
> Accept: */*
>
* Curl_http_done: called premature == 0
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
~$ curl -v https://localhost/
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 443 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 443 (#0)
* Unknown SSL protocol error in connection to localhost:-9838
* Curl_http_done: called premature == 1
* Closing connection 0
curl: (35) Unknown SSL protocol error in connection to localhost:-9838
```

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
```
version: '2'

volumes:
    ssl:
    db-data:

services:
    php:
        expose:
            - 8080
        tty: false
        restart: "on-failure:5"
        read_only: true
        mem_limit: "1g"
        memswap_limit: 0
        tmpfs: /tmp
        security_opt:
            - "no-new-privileges"

    web:
        depends_on:
            - php
        environment:
            EMAIL: xxx
        volumes:
            - ssl:/etc/caddy/.caddy
        expose:
          - 80
          - 443
        ports:
          - "80:80"
          - "443:443"
        tty: false
        restart: "on-failure:5"
        read_only: true
        mem_limit: "1g"
        memswap_limit: 0
        security_opt:
```

```
FROM alpine

RUN mkdir /etc/caddy /asset

RUN adduser -h /etc/caddy -s /bin/true -D caddy

RUN apk add -U ca-certificates

RUN apk add --no-cache --virtual deps curl tar \
    && curl -o caddy.bz "https://caddyserver.com/download/build?os=linux&arch=amd64&features=minify,expires,namecheap" \
    && tar -zxvf caddy.bz caddy \
    && mv caddy /etc/caddy/ \
    && apk del deps \
    && rm -rf caddy.bz

COPY run.sh /etc/caddy/run.sh
RUN chmod +x /etc/caddy/run.sh /etc/caddy/caddy

COPY caddyfile /etc/caddy/caddyfile

#ADD asset/ /asset/

RUN chown -R caddy:caddy /etc/caddy /asset

WORKDIR /etc/caddy
EXPOSE 80 443
VOLUME /etc/caddy/.caddy
#USER caddy

CMD /etc/caddy/run.sh
```
