### ISSUE TITLE
Reverseproxy for docker registry not working anymore

### ISSUE THREAD

**Issue by firecyberice** [mholt/caddy#1458]
### 1. What version of Caddy are you running (`caddy -version`)?
0.9.5

### 2. What are you trying to do?
I try to use caddy as reverse proxy for a docker container `gitlab/gitlab-ce:8.16.6-ce.0`
with docker registry enabled which is included in gitlab.

### 3. What is your entire Caddyfile?
```text
https://git.<fqdn> https://registry.<fqdn> {
  tls on
  tls <email for acme>
  log / /data/logs/services.log "[gitlab] - {proto} {method} {path} - {status} {size}"
  proxy / http://gitlab {
    websocket
    transparent
  }
}

```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
My caddy is running in a docker container with `caddy -type http -port 80 -http2=false -conf /data/conf/caddyfile` and published ports 80 and 443. The git part of the gitlab container is working. And with caddy 0.9.4 pushing to the registry worked too.

### 5. What did you expect to see?
docker push to registry should work.

### 6. What did you see instead (give full error messages and/or log)?
When pushing layers > ~55 MB the transmission is interrupted.
This is the caddy log_
```text
[gitlab] - HTTP/1.1 GET /jwt/auth - 200 926
[gitlab] - HTTP/1.1 POST /v2/root/example/blobs/uploads/ - 202 0
[gitlab] - HTTP/1.1 POST /v2/root/example/blobs/uploads/ - 202 0
[gitlab] - HTTP/1.1 PATCH /v2/root/example/blobs/uploads/f673486c-5e61-4d50-a2c3-0b483d385acf - 502 16
[gitlab] - HTTP/1.1 PATCH /v2/root/example/blobs/uploads/e8630147-4be3-4199-87d1-b37f41e59f8c - 502 16
```

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

The caddyfile is located at `./caddy/caddyfile` and mounted into the caddy container.
The gitlab config is located at `./config/gitlab.rb` and needs modification:
`external_url 'https://git.<fqdn'`
`registry_external_url 'https://registry.<fqdn>'`
need to be set like the domains in the caddyfile.

Use this docker-compose file to start both container:
```yaml
version: "2"
networks:
  backend:
      
services:
  caddy:
    image: firecyberice/caddy:latest
    cap_add:
      - NET_BIND_SERVICE
    ports:
      - "80:80"
      - "443:443"
    networks:
      backend:
    command: -type http -port 80 -http2=false -conf /data/caddyfile
    working_dir: /data
    environment:
      - CADDYPATH=/data
    volumes:
      - ./caddy:/data:rw

  gitlab:
    networks:
      - backend
    image: gitlab/gitlab-ce:8.16.6-ce.0
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab

```
