### ISSUE TITLE
Nil pointer errors when using websockets

### ISSUE THREAD

**Issue by passcod** [mholt/caddy#1484]
### 1. What version of Caddy are you running (`caddy -version`)?

0.9.5

### 2. What are you trying to do?

Setup Caddy as reverse HTTPS proxy over [Rancher](//rancher.com) and its Kubernetes service.

### 3. What is your entire Caddyfile?
```text
rancher.example.com
bind 0.0.0.0
log stdout
errors stderr
tls email@address.com
timeouts 0
proxy / http://rancher:8080 {
  keepalive 30
  header_upstream Host {host}
  header_upstream X-Real-IP {remote}
  header_upstream X-Forwarded-For {remote}
  header_upstream X-Forwarded-Proto {scheme}
  websocket
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

Docker-Compose section:

```yaml
caddy:
    image: abiosoft/caddy
    command: ["-conf=/etc/Caddyfile", "-agree", "-http2=false"]
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./caddy:/root/.caddy:rw
      - ./Caddyfile:/etc/Caddyfile:ro
    links:
      - rancher
```

### 5. What did you expect to see?

Rancher opening a WebSocket for its web-based kubectl console and Caddy proxying that to the backend.

### 6. What did you see instead (give full error messages and/or log)?

Caddy answered with a 500, the websocket was not passed to the backend, and Caddy logs showed this:

```
28/Feb/2017:21:50:02 +0000
[PANIC /v2-beta/projects/1a10/subscribe?eventNames=resource.change&limit=-1&sockId=12]
caddyhttp/proxy/reverseproxy.go:408 -
runtime error: invalid memory address or nil pointer dereference
```

(log message broken up on multiple lines for clarity)

This is where it's panicking: https://github.com/mholt/caddy/blob/v0.9.5/caddyhttp/proxy/reverseproxy.go#L408

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

Not sure. I'll try setting up local caddy with a sample websocket server and see if I can replicate.
