### ISSUE TITLE
Proxy in 0.10.14 leaks file descriptors

### ISSUE THREAD

**Issue by seelensonne** [mholt/caddy#2140]
### 1. What version of Caddy are you using (`caddy -version`)?

0.10.14

### 2. What are you trying to do?

Have Caddy sit in front of Prometheus [Node Exporter](https://github.com/prometheus/node_exporter) to add TLS, access control, and authentication.

### 3. What is your entire Caddyfile?

```text
host.example.com {
    bind host.example.com
    tls /path/to/cert.pem /path/to/cert.key
    ipfilter / {
        rule allow
        ip [some IP addresses]
    }
    basicauth / user password
    gzip {
        level 3
        min_length 1024
    }
    proxy /node http://localhost:9100/ {
        without /node
        transparent
    }
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

`systemctl start caddy.service` using the default `systemd` unit.

### 5. Please paste any relevant HTTP request(s) here.

`curl https://host.example.com/node/metrics`

### 6. What did you expect to see?

We upgraded from Caddy 0.10.12 to 0.10.14, and didn't expect any significant change in open file descriptors.

### 7. What did you see instead (give full error messages and/or log)?

On a host where Prometheus usually reports between 2000 and 2200 open file descriptors (metric name: `node_filefd_allocated`), we went to about 12000 in less than an hour. Something similar happened accross all our hosts.

Reverting to Caddy 0.10.12 solved the problem, i.e. `node_filefd_allocated` went back to what it was before.

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

Download Prometheus and Node Exporter from https://prometheus.io/download/.

On `prom.example.com`, start Prometheus with the following `prometheus.yml` config:

```yaml
global:
  scrape_interval: 1m
  scrape_timeout:  25s
scrape_configs:
  - job_name: node
    scheme: https
    basic_auth:
      username: user
      password: password
    metrics_path: /node/metrics
    static_configs:
      - targets:
          - host.example.com
```

On `host.example.com`, start Prometheus Node Exporter and Caddy (see above for the Caddyfile). Then wait a bit and watch the number of file descriptors increase:

```bash
$ ps ax | grep caddy # Get Caddy's PID, e.g. 19374
$ ls /proc/19374/fd | wc -l # Count file descriptors
```

With 0.10.12, the number increases a bit after start, but then stabilizes. With 0.10.14, it keeps increasing.
