### ISSUE TITLE
php $_SERVER['REQUEST_SCHEME'] is not set

### ISSUE THREAD

**Issue by kklepper** [mholt/caddy#2152]
### 1. What version of Caddy are you using (`caddy -version`)?

Caddy 0.10.14 (unofficial)

### 2. What are you trying to do?

read the information $_SERVER['REQUEST_SCHEME'] 

### 3. What is your entire Caddyfile?
```text0.0.0.0

browse

fastcgi / 127.0.0.1:9000 php

on startup php-fpm7

log stdout

errors stdout

rewrite {
    regexp .*
    ext /
    to /index.php?{query}
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

via docker compose, section abio:

```
  abio:                                                   
    build: /c/kklepper/alpine/caddy/caddy_abio
    image: kklepper/caddy_abio:alpine
    ports:
      - "8040:2015"                                  
      - "4443:443"
    depends_on:
      - hamy
    links:
      - master1:master                                     # in case we have to talk to the master directly                          
      - hamy:db_svr                                        # this is our database load balancer
      - mem                                                # memcached
      - sph                                                # sphinx search
    volumes:
      - /www:/srv
      - /c/tmp:/tmp
      - /etc/localtime:/etc/localtime
    networks:
      - front
      - back
```

### 5. Please paste any relevant HTTP request(s) here.

http://test.b2d:8040/about 

(local network, server runs on Boot2Docker (Tiny Core Linux), client on Windows)

### 6. What did you expect to see?

No error

Apache and Nginx can do, Caddy not. In consequence the source code depending on this information fails.

### 7. What did you see instead (give full error messages and/or log)?

```
A PHP Error was encountered

Severity: Notice

Message: Undefined index: REQUEST_SCHEME
```
### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

clone abiosoft/caddy-docker, e.g.

```
docker@boot2docker:/c/kklepper/alpine/caddy$ git clone https://github.com/abiosoft/caddy-docker.git
docker@boot2docker:/c/kklepper/alpine/caddy$ cd caddy-docker
```

edit php/index.php

```
docker@boot2docker:/c/kklepper/alpine/caddy/caddy-docker$ cd php
docker@boot2docker:/c/kklepper/alpine/caddy/caddy-docker$ nano index.php
```

add before the line with phpinfo() 

```
    ini_set("display_errors", 1);
    echo "Here is the error: _SERVER['REQUEST_SCHEME'] ={$_SERVER['REQUEST_SCHEME']}=";
```
    
build the system:

```
docker@boot2docker:/c/kklepper/alpine/caddy/caddy-docker$ docker build -f Dockerfile$dver -t kklepper/${PWD##*/}$dver:alpine . && docker images | grep 'none>'| awk {'print $3'} |xargs docker rmi
```
start the container

```
docker@boot2docker:/c/kklepper/alpine/caddy/caddy-docker/php$ docker run -d -p 2015:2015 --name test kklepper/php:alpine
e44b94e1a104e43c9fb0d4c061a059f19c72da20a4c061770d17a0b640deac58
```
check the output

```
docker@boot2docker:/c/kklepper/alpine/caddy/caddy-docker/php$ curl -s localhost:2015 | grep Notice
<b>Notice</b>:  Undefined index: REQUEST_SCHEME in <b>/srv/index.php</b> on line <b>22</b><br />
```
