### ISSUE TITLE
Proxy "without" broken again

### ISSUE THREAD

**Issue by ddavidebor** [mholt/caddy#2261]
### 1. What version of Caddy are you using (`caddy -version`)?
0.11.0
### 2. What are you trying to do?
have urls like linuxserver.mydomain.it/myapp/ proxy to linuxcontainer

### 3. What is your entire Caddyfile?
```text
serverlinux.mydomain.it {
        log stdout
        tls off
        root /var/www
        proxy /electronicdblibs dblibsviewer:8000 {
                without /electronicdblibs
                transparent
                websocket
        }
        markdown / {
        }
        
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

```
used docker-compose

version: '3'
services:
  dblibsviewer:
    image: reelsrl/dblibsviewer
    build: dblibsviewer
    expose:
     - "8000"
    volumes:
     - ./dblibsviewer/app:/usr/src/app/
    restart: always
  caddy:
    image: abiosoft/caddy:latest
    ports:
     - "80:2015"
    volumes:
    - ./caddy/Caddyfile:/etc/Caddyfile
    - ./caddy/www/:/var/www
    environment:
    - ACME_AGREE=true
    restart: always
```

### 5. Please paste any relevant HTTP request(s) here.

This is what is received by my app

`dblibsviewer_1  | 172.18.0.3 - - [08/Aug/2018:14:00:14 +0000] "POST /api HTTP/1.1" 200 1056 "http://serverlinux.mydomain.it/electronicdblibs/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36"
`

for some reason /electronicdblibs is not removed

### 6. What did you expect to see?

`dblibsviewer_1  | 172.18.0.3 - - [08/Aug/2018:14:00:14 +0000] "POST /api HTTP/1.1" 200 1056 "http://serverlinux.mydomain.it/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36"
