### ISSUE TITLE
-quiet flag suppresses list of addresses being served from all outputs

### ISSUE THREAD

**Issue by whitestrake** [mholt/caddy#2473]
## 1. Which version of Caddy are you using (`caddy -version`)?
Caddy 0.11.4 (unofficial)

## 2. What are you trying to do?
Run `caddy -quiet` to avoid duplication of list of addresses on startup when process log is set to `stdout`.

## 3. What is your Caddyfile?
```text
kairos.whitestrake.net
tls {
  dns cloudflare
}
rewrite / /
root /srv
```

## 4. How did you run Caddy (give the full command and describe the execution environment)?
Docker Compose:

```
version: '3'
services:

  caddy:
    build:
      context: github.com/abiosoft/caddy-docker.git
      args:
        - plugins=git,cloudflare
    command: ["-log", "stdout", "-agree", "-quiet",
      "-email", "letsencrypt@whitestrake.net",
      "-conf", "/etc/Caddyfile"]
    environment:
      CLOUDFLARE_EMAIL:  [snip]
      CLOUDFLARE_API_KEY: [snip]
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile:/etc/Caddyfile
      - ./caddy/certificates:/root/.caddy
      - ./caddy/srv:/srv
```

## 5. Please paste any relevant HTTP request(s) here.
N/A

## 6. What did you expect to see?
A single set of addresses (i.e. no duplicates in `stdout`).

## 7. What did you see instead (give full error messages and/or log)?
No list of addresses _at all_, not to the process log or to the regular `stdout` output!

```
whitestrake in ~ at kairos is 🐳 v18.09.1
➜ dc logs -f --tail 20 caddy
Attaching to whitestrake_caddy_1
caddy_1  | 2019/02/20 00:22:01 [INFO][FileStorage:/root/.caddy] Started certificate maintenance routine
caddy_1  | 2019/02/20 00:22:02 [NOTICE] Sending telemetry: we were too early; waiting 1h1m20.852339543s before trying again
caddy_1  | 2019/02/20 00:22:31 [INFO] SIGUSR1: Reloading
caddy_1  | 2019/02/20 00:22:31 [INFO] Reloading
caddy_1  | 2019/02/20 00:22:31 [INFO][FileStorage:/root/.caddy] Started certificate maintenance routine
caddy_1  | 2019/02/20 00:22:31 [INFO] Reloading complete
caddy_1  | 2019/02/20 00:22:31 [INFO][FileStorage:/root/.caddy] Stopped certificate maintenance routine
caddy_1  | 2019/02/20 00:30:15 [INFO] 149.28.170.170 - No such site at :80 (Remote: 131.161.34.13, Referer: )
```

## 8. Why is this a bug, and how do you think this should be fixed?
I expected `-quiet` to suppress regular startup output, not to affect the process log at all.

This is at odds both with my expectation and the documentation itself: https://caddyserver.com/docs/cli#quiet

The documentation asserts that list of addresses will be printed regardless of its usage.

## 9. What are you doing to work around the problem in the meantime?
Deal with the extra log lines.

## 10. Please link to any related issues, pull requests, and/or discussion.
#2469 is touching code quite close to this problem; perhaps it could be fixed as part of that PR by @tobya. It isn't currently being addressed by the proposed changes.

The cause of this issue is that currently, in `server.go`, we skip _all_ address list output if `caddy.Quiet` is set:

https://github.com/mholt/caddy/blob/396d8e989ffdca4bb5aac2d01d5f4f48c44a6291/caddyhttp/httpserver/server.go#L510-L512

Currently in #2469 we still have that behaviour:

https://github.com/mholt/caddy/blob/5d6700a9c4927b2f05faea660296893954b8fcc6/caddyhttp/httpserver/server.go#L510-L512

In my opinion, instead we should check for `caddy.Quiet` before printing the regular output but not before printing the process log output. The docs should also be updated to indicate its actual behaviour.
