### ISSUE TITLE
json api format

### ISSUE THREAD

**Issue by coolaj86** [mholt/caddy#322]
forking discussion from https://github.com/mholt/caddy/issues/310

[That json](https://github.com/mholt/caddy/blob/master/caddy/caddyfile/json_test.go) looks more like a syntax tree than a data specification. You're using all arrays because you're parsing the file as arrays (because you don't want the end user to concern themselves with the difference between an array and a key/value pair, and your keys never have spaces so you can use space instead of ':'), but the data actually represents key/value pairs.

There are only 3 basic data types represented in caddy (and the universe at large):

* single values
* key/value pair (named) collections
* anonymous collections

I would recommend creating a spec for json that accurately represents a caddyfile in those terms and then handling the transform in the parser area. This means an extra step for a caddyfile to json converter (because it parses it what what it means as an object in memory), but is more semantic to json and more obvious to a casual observer / new dev.

In JSON there should never be a value that is sometimes an array but sometimes a singleton. Likewise there should never be a value that is sometimes an array but sometimes a key/value pair. This is important for machines to be able to automatically parse data as well as humans. The entire XML debacle hung around not being able to definitively know if something was an array (multiple tags of the same name vs an array tag), or a key value pair (text inside of a tag vs an attribute of a tag) or metadata (comments and attributes).

So this example as a caddy file (which is semantically a lot like XML - no implicit distinction of data types, completely parser defined):

```
# root level directives are allowed, right?
gzip

https://config.* {
   tls /le/{host}/fullchain.pem /le/{host}/privkey.pem
   proxy /api http://localhost:4080
   root {
     /common-scripts/ /srv/walnut/common-scripts
     / /srv/walnut/config.app
   }
}

https://0.0.0.0 {
   tls /le/{host}/fullchain.pem /le/{host}/privkey.pem
   proxy /protected http://localhost:4080
   proxy /api http://localhost:4080
   root {
     /common-scripts/ /srv/walnut/common-scripts
     / /srv/walnut/sites-enabled/{host}
   }
}
```

Since, unlike XML, Caddyfile is not a general purpose or extensible type, each of its types may be well-defined.

As such we can unambiguously represent it as json (which requires data type distinction) like this:

```json
{
  "global": {
    "gzip": true
  }
, "hosts": {
    "https://config.*": {
      "tls": ["/le/{host}/fullchain.pem", "/le/{host}/privkey.pem"]
    , "proxy": {
        "/protected": "http://localhost:4080"
      , "/api": "http://localhost:4080"
      }
    , "root": {
        "/common-scripts/": "/srv/walnut/common-scripts"
      , "/": "/srv/walnut/config.app"
      }
    }
  , "https://0.0.0.0": {
      "tls": ["/le/{host}/fullchain.pem", "/le/{host}/privkey.pem"]
    , "proxy": {
        "/protected": "http://localhost:4080"
      , "/api": "http://localhost:4080"
      }
      , "root": {
        "/common-scripts/": "/srv/walnut/common-scripts"
      , "/": "/srv/walnut/sites-enabled/{host}"
      }
    }
  }
}
```

And would be this as yaml:

```yaml
# could put anything global as "global", or attach it to the root object, or add it to each host
global:
  gzip: true

# could put everything that isn't a directive under hosts
hosts:
  https://config.*:
    tls:
      - /le/{host}/fullchain.pem
      - /le/{host}/privkey.pem

    # anything that can be specified multiple times is probably a k/v collection
    proxy:
      /protected: http://localhost:4080
      /api: http://localhost:4080

    root:
      /common-scripts/: /srv/walnut/common-scripts
      /: /srv/walnut/config.app

  https://0.0.0.0:
    tls:
      - /le/{host}/fullchain.pem
      - /le/{host}/privkey.pem

    proxy:
      /protected: http://localhost:4080
      /api: http://localhost:4080

    root:
      /common-scripts/: /srv/walnut/common-scripts
      /: /srv/walnut/sites-enabled/{host}
```
