### ISSUE TITLE
markdown: Custom templates and front matter

### ISSUE THREAD

**Issue by mholt** [mholt/caddy#35]
Right now, the markdown directive only lets you specify CSS and JS files. It would be really useful to be able to specify a full page template like you can with the browse middleware.

Markdown should also be expanded to support front matter that contains metadata, etc... it could be used to fill template values and render the page.

**Comment by abiosoft** [comment]
These are my thoughts so far.

Support for front matters, both sitewide and each page. Example below.
```toml
---
title = "Page Title"
js = [ "jquery.js", "script.js" ]  
css = [ "bootstrap.css", "style.css" ]

[variables]
name = "Matt"
date = "May 1, 2015"

[[meta]]
charset = "UTF-8"

[[meta]]
name = "description"
content = "Caddy Markdown Page"

[[meta]]
name = "keywords"
content = "caddy, markdown"

[[meta]]
name = "author"
content = "Matt Holt"
---
[Page markdown contents goes here]
```
* Front matter sample above specified in [TOML](https://github.com/toml-lang/toml) syntax. (debatable)
* Front matter can be embedded in a page by preceding and proceeding with `---` or in a separate file (see Caddyfile below).
* Title, multiple js and multiple css can be specified as shown above.
* Variables are defined under `[variables]` and will be accessible using standard Go template e.g. `{{name}}` within page contents. There can also be some useful predefined variables like current date.
* Multiple meta tags can be specified using array of dictionaries. Example above.

Caddyfile syntax, backward compatible and with new **front** keyword.

Syntax: `front path filepath`
path - request path relative to the site
filepath - path to the toml file

All pages on that path will be rendered using the config in the specified toml file. If there are conflicting configs (mainly variables), the one embedded in page will be preferred.
```
markdown /blog {
    ext .md .txt
    css /resources/css/blog.css
    js  /resources/js/blog.js
    front /projects /projects/projects.toml
    front / /blog.toml
}
```
Does this looks practical and feasible ? 

Thanks.
