### ISSUE TITLE
Received SIGTERM right after "Updating OCSP stapling to extend validity period" (systemd)

### ISSUE THREAD

**Issue by hubertbanas** [mholt/caddy#505]
```
uname -a
Linux servername 4.1.6-249 #1 SMP Mon Aug 31 12:34:47 UTC 2015 armv7l GNU/Linux
```
```
cat /etc/debian_version
8.2
```
```
/etc/systemd/system/caddy.service
[Unit]
Description=Caddy webserver
Documentation=https://caddyserver.com/
After=network.target

[Service]
User=caddy
LimitNOFILE=4096
ExecStart=/opt/caddy/caddy -agree=true -conf=/etc/caddy/Caddyfile -pidfile=/var/run/caddy/caddy.pid -log=stderr
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

```
Jan 12 16:46:22 servername caddy[16660]: 2016/01/12 16:46:22 [INFO] Updating OCSP stapling to extend validity period to 2016-01-19 14:00:00 +0000 UTC
Jan 12 16:46:23 servername caddy[16660]: 2016/01/12 16:46:23 [INFO] Checking certificates for 26 hosts
Jan 12 16:46:23 servername caddy[16660]: 2016/01/12 16:46:23 [INFO] SIGTERM: Terminating process
```

This is when running 060ab92d295ba9dd8e34115c92557d5eff5896ff. I'm planning to step up to 0.8.1 3c96718027db0fc6bf40837b2983f849578b5f7f sometime tomorrow.

Let me know what debug data is needed.

**Comment by mholt** [comment]
Is this a Caddy question or a systemd question? Because I don't see anything wrong with this...

**Comment by hubertbanas** [comment]
Is this behavior expected? And if so what would be the recommended way to handle it.

**Comment by mholt** [comment]
I guess I'm not understanding the question -- are you asking if Caddy is SIGTERM'ing itself?

**Comment by hubertbanas** [comment]
I'm sorry, I should give you some background information first. I had Caddy running for about 6 hours serving multiple websites with no issues. According to the log at 16:46:22 "Updating OCSP stapling to extend validity period to" comes in and 1 second later at 16:46:23 Caddy dies with "SIGTERM: Terminating process". At this point Caddy remains down. I'm not really sure if we're looking at systemd or caddy issue.

**Comment by mholt** [comment]
Thanks for the background. That's helpful :smile:

Caddy is certainly not signaling itself. As stated [in the docs](https://caddyserver.com/docs/automatic-https), Caddy will restart when certificate information is updated, and this gives it a new process ID. I bet this is a systemd issue.

**Comment by Xe** [comment]
Why is it killing itself at all?

**Comment by mholt** [comment]
It's not -- I'm not sure what is signaling Caddy to terminate. But Caddy will respawn when it updates its listeners (certificates, OCSP stuff, etc); this allows it to do so immediately and without downtime, avoiding a mess of locking and blocking requests.

**Comment by hubertbanas** [comment]
It happened again at 21:48:20. 

```
Jan 12 21:48:20 servername caddy[18886]: 2016/01/12 21:48:20 [INFO] Updating OCSP stapling to extend validity period to 2016-01-19 14:00:00 +0000 UTC
Jan 12 21:48:22 servername caddy[18886]: 2016/01/12 21:48:22 [INFO] Checking certificates for 26 hosts
Jan 12 21:48:27 servername caddy[18886]: 2016/01/12 21:48:27 [INFO] SIGTERM: Terminating process
```

Monit started the process and it is running again. I'm not sure where to take it from here.

**Comment by mholt** [comment]
I would try running it without systemd, (`caddy &` maybe?) and see what happens -- I'd be interested to know if it's still term'ing.

**Comment by hubertbanas** [comment]
How often Caddy performs OCSP stapling? Is this hard coded? Can we manipulate the value? The reason I'm asking is to help recreating the issue. My last Caddy restart was 21 hours ago and I'm still waiting for OCSP stapling.

**Comment by mholt** [comment]
Currently, Caddy maintains a list of the OCSP responses and iterates them every hour. It checks the LastUpdate and NextUpdate fields and, if that validity period is halfway over, it requests new OCSP. If it finds that the validity window has shifted more into the future (a new NextUpdate value), that's when it triggers a reload, printing those log lines you see.

It may take a couple days for new OCSP data.

**Comment by hubertbanas** [comment]
Thanks for the explanation. 

Just got one. This is still using systemd running the latest 0.8.1
```
Jan 15 11:16:01 servername caddy[10832]: 2016/01/15 11:16:01 [INFO] Updating OCSP stapling to extend validity period to 2016-01-22 13:00:00 +0000 UTC
Jan 15 11:16:01 servername caddy[10832]: 2016/01/15 11:16:01 [WARNING] TLS disabled for http://0.0.0.0:80.
Jan 15 11:16:01 servername caddy[10832]: 2016/01/15 11:16:01 [WARNING] TLS disabled for http://111.222.333.444:80.
Jan 15 11:16:06 servername caddy[10832]: 2016/01/15 11:16:06 [WARNING] TLS disabled for http://0.0.0.0:80.
Jan 15 11:16:06 servername caddy[10832]: 2016/01/15 11:16:06 [WARNING] TLS disabled for http://111.222.333.444:80.
Jan 15 11:16:15 servername caddy[10832]: 2016/01/15 11:16:15 [INFO] Checking certificates for 28 hosts
Jan 15 11:16:54 servername caddy[10832]: 2016/01/15 11:16:54 [INFO] SIGTERM: Terminating process
```

I see two interesting facts:
1) "TLS disabled" appears twice for the same IPs 5 seconds apart
2) SIGTERMing 39 seconds after "Checking certificates". Could this be somehow related to #507 

I'm going to try running from the command line as you suggested. This is to rule out potential systemd issue. Unless you would prefer different course of action?

**Comment by mholt** [comment]
Thanks - yes, do that and let me know how it goes.

**Comment by hubertbanas** [comment]
Received ```Updating OCSP stapling``` twice since starting from the command line and there is no failure. Which points to possible systemd issue. We need some systemd guru to take a look at my ```/etc/systemd/system/caddy.service```. Maybe there is something unordinary that would need to be changed?

Here is the version I'm running
```
-->systemd --version
systemd 215
```

I know the right thing to do would be to close this issue but I would like to keep it open for now if that is OK with you. Maybe changing the title only?

**Comment by mholt** [comment]
Sure. Also will you try this binary? I built it for ARM Linux and it has a heck of a LOT more logging, could be useful for all your open issues right now. https://drive.google.com/file/d/0B-OxZ0LoeTvGT2E3dExiRFp4Zzg/view?usp=sharing

**Comment by Xe** [comment]
@hubertbanas I am a systemd guru. I use [this unit](https://github.com/Xe/rpmspecs/blob/master/caddy/caddy.service) for my caddy deployments. What's the content of yours?

**Comment by hubertbanas** [comment]
@mholt 
Thanks. I will take it for a spin

@Xe
```
[Unit]
Description=Caddy webserver
Documentation=https://caddyserver.com/
After=network.target

[Service]
User=caddy
LimitNOFILE=4096
ExecStart=/opt/caddy/caddy -agree=true -conf=/etc/caddy/Caddyfile -pidfile=/var/run/caddy/caddy.pid -log=stderr
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

I see you have WorkingDirectory in your service file. Can you please elaborate?

**Comment by Xe** [comment]
```console
xena@greedo (linux) ~
➜  sudo -iu caddy
[sudo] password for xena:
[caddy@greedo ~]$ ls -la
total 28
drwx------  3 caddy caddy  150 Jan  8 20:03 .
drwxr-xr-x 34 root  root  4096 Jan 10 21:46 ..
-rw-------  1 caddy caddy 1283 Jan 12 13:08 .bash_history
-rw-r--r--  1 caddy caddy   18 Aug 18 06:37 .bash_logout
-rw-r--r--  1 caddy caddy  193 Aug 18 06:37 .bash_profile
-rw-r--r--  1 caddy caddy  231 Aug 18 06:37 .bashrc
drwx------  3 caddy caddy   32 Jan  8 20:03 .caddy
-rw-r--r--  1 caddy caddy  334 Sep 11 10:02 .emacs
-rw-r--r--  1 caddy caddy  658 Dec 25 04:14 .zshrc
[caddy@greedo ~]$ ls -la .caddy
total 0
drwx------ 3 caddy caddy  32 Jan  8 20:03 .
drwx------ 3 caddy caddy 150 Jan  8 20:03 ..
drwx------ 4 caddy caddy  42 Jan  8 20:03 letsencrypt
[caddy@greedo ~]$
```

Caching the Let's Encrypt certs.

**Comment by hubertbanas** [comment]
OK, I can start with that. Sorry but your ```ls``` doesn't show the full path. Are your certs at /var/lib/caddy ?

**Comment by Xe** [comment]
```console
[caddy@greedo letsencrypt]$ tree /var/lib/caddy/.caddy/
/var/lib/caddy/.caddy/
└── letsencrypt
    ├── sites
    │   ├── xena.greedo.xeserv.us
    │   │   ├── xena.greedo.xeserv.us.crt
    │   │   ├── xena.greedo.xeserv.us.json
    │   │   └── xena.greedo.xeserv.us.key
    │   └── znc.yolo-swag.com
    │       ├── znc.yolo-swag.com.crt
    │       ├── znc.yolo-swag.com.json
    │       └── znc.yolo-swag.com.key
    └── users
        ├── me@christine.website
        │   ├── me.json
        │   └── me.key
        └── xena@yolo-swag.com
            ├── xena.json
            └── xena.key

7 directories, 10 files
```

**Comment by hubertbanas** [comment]
Awesome! Thank you!

**Comment by Xe** [comment]
relevant ansible plays I use:

```yaml
# https://github.com/Xe/dotfiles/blob/master/ansible/roles/caddy/tasks/user.yml
- name: create caddy user
  user: name=caddy system=yes home=/var/lib/caddy
```

```yaml
# https://github.com/Xe/dotfiles/blob/master/ansible/roles/caddy/tasks/install.yml
- name: enable caddy repo
  get_url:
    url: https://copr.fedoraproject.org/coprs/xena/caddy/repo/fedora-23/xena-caddy-fedora-23.repo
    dest: /etc/yum.repos.d/caddy.repo

- name: install caddy
  dnf:
    name: caddy
    state: latest

- name: install systemd unit
  copy:
    src: caddy.service
    dest: /etc/systemd/system/caddy.service
  notify: enable caddy
```

```yaml
# https://github.com/Xe/dotfiles/blob/master/ansible/roles/caddy/tasks/config.yml
- name: create caddy folders
  file: path={{ item }} state=directory
  with_items:
    - /etc/caddy
    - /etc/caddy/sites

- name: copy Caddy config to /etc/caddy/Caddyfile
  copy:
    src: Caddyfile
    dest: /etc/caddy/Caddyfile
  notify: restart caddy

- name: copy sites config
  copy:
    src: "sites/{{ item }}"
    dest: "/etc/caddy/sites/{{ item }}"
  with_items:
    - xena.greedo.xeserv.us
    - znc.yolo-swag.com
  notify: restart caddy
```

Caddyfile:
```
import /etc/caddy/sites/*
```

`/etc/caddy/sites/xena.greedo.xeserv.us`:
```
xena.greedo.xeserv.us {
	log syslog

	tls me@christine.website

	root /home/xena/public_html

	markdown / {
		template blog templates/blog.html
		template index templates/index.html
	}

	browse
}
```

Hope this helps!
