### ISSUE TITLE
docker-compose 502s on some machines

### ISSUE THREAD

**Issue by princemaple** [mholt/caddy#808]
#### 1. What version of Caddy are you running (`caddy -version`)?
0.8.3
docker 1.11.1
compose 1.7

#### 2. What are you trying to do?
run caddy with docker-compose

#### 3. What is your entire Caddyfile?
```
http://localhost {
  log / stdout "{host} {upstream}"
  proxy / web:8080 {
    proxy_header Host {host}
    proxy_header X-Real-IP {remote}
    proxy_header X-Forwarded-Proto {scheme}
  }
}
```
and docker-compose.yml
```yaml
version: '2'
services:
  caddy:
    image: zzrot/alpine-caddy:v0.8.3
    ports:
      - 80:80
    volumes:
      - ./Caddyfile:/etc/Caddyfile
    depends_on:
      - web
  web:
    image: ehazlett/docker-demo
    ports:
      - 8080
```
**NOTE:** I also tried @abiosoft abiosoft/caddy to make sure it's not a problem in the docker image.

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
```
docker-compose up -d
```

#### 5. What did you expect to see?
Everything works; I can `curl localhost` to get the html

#### 6. What did you see instead (give full error messages and/or log)?
On my local boot2docker, it does work as expected
On a VPS, I tried several Linux distributions, it didn't work on any of them, not sure what's wrong.
The result was simply 502, Caddy couldn't find the backend. Funny thing is, I tried `ping` and `curl` in Caddy container, they worked as expected.

#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
Use the provided `docker-compose.yml` and `Caddyfile` and run `docker-compose up`. Not sure how you could reproduce 502s though, it works in boot2docker. The server I'm using is scaleway.com.

I did find one way (workaround) to make Caddy able to find the backend, which is setting a network alias for the backend service

swap the `web` part in the compose file above with the following:
```yaml
web:
  image: ehazlett/docker-demo
  ports:
    - 8080
  networks:
    default:
      aliases:
        - app
```

and 

```diff
-  proxy / web:8080 {
+  proxy / app:8080 {
```

**Comment by princemaple** [comment]
It's probably not a bug in Caddy, I just want to know if someone happens to know the solution to the problem I've encountered.

**Comment by wmark** [comment]
The configuration the Docker daemon is started with is important here. My guess is that this is not about *Caddy* at all.

Please share the output of these commands with us:

```bash
$ sudo ps -C docker -o pid,user,args --sort pid

$ docker network ls
```

**Comment by princemaple** [comment]
```
  PID USER     COMMAND
 9206 root     /usr/bin/docker daemon -H fd:// -H unix:///var/run/docker.sock --storage-driver aufs --label provider=scaleway --mtu=1500
```

```
NETWORK ID          NAME                DRIVER
481ecd6911ec        app_default         bridge
97221b6c10fb        bridge              bridge
2b868ca6943d        host                host
a15cd0ef227f        none                null
```

Yeah I too don't think it's about Caddy, just trying to see if someone knows how to solve this already. I ran out of ideas to try.

**Comment by wmark** [comment]
Which one is this? Please post the output for both cases. ;-)

**Comment by princemaple** [comment]
> Please post the output for both cases. ;-)

I did...
Edited to have both the command and the output, hopefully that makes it clear.

**Comment by wmark** [comment]
Case 1: runs, case 2: doesn't.

**Comment by wmark** [comment]
@princemaple Do you have the output from two installations, representing the two cases? Or, did you spot a difference and this is resolved?

**Comment by princemaple** [comment]
Hi @wmark could you clarify what case 1 & 2 you are referring to?
If you are testing my initial setup as case 1 & my workaround as case 2, the complete docker-compose.yml should be:

```yml
version: '2'
services:
  caddy:
    image: zzrot/alpine-caddy:v0.8.3
    ports:
      - 80:80
    volumes:
      - ./Caddyfile:/etc/Caddyfile
    depends_on:
      - web
  web:
    image: ehazlett/docker-demo
    ports:
      - 8080
    networks:
      default:
        aliases:
          - app
```

**Comment by wmark** [comment]
1. SSH into the VM where it works, run the two commands, post the output. (case »works«)
2. SSH into a machine where it does not work, run the two commands, post the output. (case »doesn't«)

**Comment by princemaple** [comment]
I see what you mean now. Updated the previous comment to include the outputs from boot2docker.

**Comment by princemaple** [comment]
They do differ quite significantly. Wow.

**Comment by wmark** [comment]
The important bit is that in both cases a *bridge* has been created for both containers (probably called app_default and test_default). I assume they are connected to said bridge(s):

```sh
docker inspect app_caddy_1 | grep -F NetworkID
docker inspect app_web_1 | grep -F NetworkID
```

Now's the question, does the container containing *Caddy* (1) resolve a host **web**, (2) can connect to the host:

```sh
$ docker exec -ti caddytest_caddy_1 /bin/sh
# ping -c 2 web
# exit
```

```sh
$ docker exec -ti caddytest_caddy_1 /bin/sh
# wget http://web:8080/ -O -
```

(You Caddyfile binds to a name "localhost", which is no wise choice for the tests here, but anyway.)

**Comment by princemaple** [comment]
> 6. What did you see instead (give full error messages and/or log)?
> 
> On my local boot2docker, it does work as expected
> On a VPS, I tried several Linux distributions, it didn't work on any of them, not sure what's wrong.
> The result was simply 502, Caddy couldn't find the backend. Funny thing is, I tried ping and curl in Caddy container, they worked as expected.

@wmark thanks for following this up so closely! I actually have tested this before and had this written in the issue description. I can reach to the `web` container from the `caddy` container in either case, caddy works or not. That why I thought there is a slight chance that caddy and docker might be together contributing to the seen problem, and someone in caddy community could help me out :)

**Comment by princemaple** [comment]
boot2docker machine was created using docker machine, and the VPS machine was simply created with docker installed. I could try and create another machine on the VPS with docker-machine, and see if it works out. That will be very interesting, I think.

**Comment by wmark** [comment]
I will try to reproduce this on Scaleway/{amd64,arm}. This could be a race condition somewhere.

In the meanwhile you could try this option for directive *proxy*: ```max_fails 0```

**Comment by wmark** [comment]
I can reproduce this.

**Comment by princemaple** [comment]
> I can reproduce this.

:tada: , oh wait. :)

> With max_fails 0 Caddy just hangs.

Yep, that's right. Same behavior here.

**Comment by princemaple** [comment]
> (There's no curl in zzrot/alpine-caddy, hence I assumed you tested from the host, not the container.)

that's based on an alpine linux image, to get curl: `apk update && apk add curl`, should take like 3 seconds.

**Comment by princemaple** [comment]
> This could be a race condition somewhere.

yeah I'd suspect so as well. docker injects dns stuff into containers, does caddy cache dns resolution at all? (I'm total noob at Go and DNS, and don't really know where to look in the code)

**Comment by mholt** [comment]
@princemaple It does DNS resolution if you give it a domain name to resolve, like `web` in your case.

**Comment by princemaple** [comment]
Hi @mholt thanks for the reply.

Does it cache though? If so, does it retry if the initial lookup failed?
If this was a race condition in dns resolution, it might be solvable on Caddy side...

**Comment by mholt** [comment]
No, Caddy doesn't cache the lookups (not explicitly). The method of performing the DNS lookup depends how Caddy was built, too. If you build with CGO_ENABLED=0 (as the website does and the official releases are), it uses Go's built-in DNS resolver, otherwise it uses the system resolver. I don't think Go's built-in DNS resolver does any caching.

I'm out of my league with Docker questions (thanks @wmark for heading this up), but the only thing that concerns me is the max_fails=0 causing Caddy to "hang". Is it really hanging or is it spinning? Spinning is expected, hanging is not.

**Comment by princemaple** [comment]
@mholt it hangs.

I tested again with this setup
*the server has a running app so I had to map ports around, but trust me here that the request does hit the right endpoint*
```
http://localhost {
  log / stdout "{host} {upstream}"
  errors stdout

  proxy / abc:8080 {
    fail_timeout 2s
    max_fails 0
    proxy_header Host {host}
    proxy_header X-Real-IP {remote}
    proxy_header X-Forwarded-Proto {scheme}
  }
}
```
```yaml
version: '2'
services:
    caddy:
        image: abiosoft/caddy:0.8.3
        ports:
            - 8080:80
        volumes:
            - ./Caddyfile:/etc/Caddyfile
        depends_on:
            - web
    web:
        image: ehazlett/docker-demo
        ports:
            - 8080
```
running `curl -v localhost:8080` gives me
```
* Rebuilt URL to: localhost:8080/
*   Trying ::1...
* Connected to localhost (::1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.43.0
> Accept: */*
>
♥
```
I had to `ctrl+c` there.

**Comment by wmark** [comment]
That's been my checklist:

 1. Did Docker create a network, and did the containers get attached to it correctly? (This failed for me with earlier version of Docker Compose.)
 2. … or is there a network driver configured for Docker?
 3. … or, is Docker Swarm used?
 4. Is »web« started before »Caddy«?
 5. Did Docker inject its »/etc/hosts« file (if at all)?
 6. Did Docker make available its DNS resolver? Did the resolver get picked up by Go/Caddy (has »/etc/resolv.conf« with a 127.0.0.11 get read) or is Go/Caddy using a fallback resolver (8.8.8.8 or something like that hard-coded)?

If it's (6), then »/etc/resolv.conf« will be read when running *ping*. Which is the case. But then a second Caddy instance, started manually, wouldn't run into that *race condition* and use Docker's resolver, working as intended. — This is not that case.

I've added the IP of container »web« to »/etc/hosts« and there's been no error 502 (BadGateway).

I did find out what's going on. It's boils down to one silly thing, and you will be amazed when hearing this after the break.

**Comment by princemaple** [comment]
> Is »web« started before »caddy«?

Yeah we can assure that with `depends_on`

> Did Docker inject its `/etc/hosts` file (if at all)?

> I've added container »web's« IP to /etc/hosts and error 502 (BadGateway) is gone.

Yes adding the ip to `/etc/hosts` can solve this problem, it is the case if you use docker-compose with a compose v1 file. However, using compose v2 file, with or without swarm, won't interpolate `/etc/hosts` for you, so we have to get the DNS resolution working somehow.

> Did Docker make available its DNS resolver? Did the resolver get picked up by Go/Caddy (has /etc/resolv.conf with a 127.0.0.11 get read) or is Go/Caddy using a fallback resolver (8.8.8.8 or something like that hard-coded)?

That's what I'm most interested in as well :+1: 

> I did find out what's going on. It boils down to one silly thing, and you will be amazed when hearing it after the break.

:eyes: Amaze me please! (hopefully it has nothing to do with `/etc/hosts`, because we can't rely on that if running swarm)

Thanks for all the effort you put in, @wmark 
Really appreciate it.

**Comment by wmark** [comment]
```/etc/resolv.conf``` is copied by Docker from the host with some adjustments. The relevant part that contributed to failure is a line like this (the first one):
```
search cloud.online.net
options ndots:0
```

Caddy uses Go, and Go is to lookup ```web```. Only that the suffix given by *search* is appended unconditionally (which is a bug), and DNS queries for ```web.cloud.online.net``` are sent. The host does not exists and Caddy throws rightfully HTTP Error 502.

It's a bug in Go's resolver because the number of dots in domain name ```web``` is 0, and that's ≤```ndots:0```, which says when to start appending from a directive ```search```.

I will file a bug report with Go's authors shortly.

Please feel free to open new ticket with *Caddy* for the ```proxy: Caddy hangs with max_fails 0 and a unresolved host```.

**Comment by wmark** [comment]
A workaround with Docker is to use a named network and aliases. With a name ```appnet``` the hostname would be ```backend.appnet``` (backend → web).

```yaml
version: '2'
services:
  caddy:
    container_name: frontend
    image: zzrot/alpine-caddy:v0.8.3
    ports:
      - 80:80
    volumes:
      - ./Caddyfile:/etc/Caddyfile
    depends_on:
      - backend
    networks:
      - appnet

  backend:
    image: ehazlett/docker-demo
    ports:
      - 8080
    networks:
      appnet:
        aliases:
          - backend.appnet

networks:
  appnet:
```

```sh
# this does not work with version 2! variables cannot be keys
# env NETNAME=appnet ./docker-compose-1.7.0 up -d

./docker-compose-1.7.0 up -d
```
